### PR TITLE
Fixed bug where it wouldn't send the order number

### PR DESCRIPTION
**Pull request by Smirf123**
I managed to find a bug, where it wouldn't link correctly so I updated the links and embed names.

### CODE REVIEW

**Comment by metallicgloss** [comment]
Was there a specific exception that occured during this? The set to pending worked as expected, and the hook should have the order ID parameter to allow for this to work correctly.

**Comment by Smirf123** [comment]
When it sent the webhook notice to my server, it just went blank for no reason.

**Comment by metallicgloss** [comment]
I will check into this a little further, as I feel that having a very generic notification that doesn't display the number nor link provides any added benefit to the addition.

**Comment by bgbuddyboy** [comment]
> @Smirf123 Shouldn't it just be `orderId` in the `$vars` array? https://developers.whmcs.com/hooks-reference/shopping-cart/#orderpaid

Yes this is correct and working for me.
WHMCS need to be more consistent with their variable naming.

**Comment by JayRusson** [comment]
For some reason I can’t make a new enhancement thread…

Could we look to add the following hooks:
Order Suspended
Order Suspension Failed
Module Create Failed 

I’ve managed to sorta give it a shot but can’t work out the links for the embeds actually pointing to the specific product or service

**Comment by metallicgloss** [comment]
@JayRusson

This module is primarily defined by the "Hooks" that WHMCS provides [here](https://developers.whmcs.com/hooks/hook-index/),  so when it comes to "Order Suspended" or "Order Suspension Failed", there is, unfortunately, no hook to be able to detect that. You could look to expand the functionality using "After Module Suspend" on a per-service basis.

With regards to the "Module Create Failed", there are some additional hooks you could extend the module to include - for this action, there is a hook for that [here](https://developers.whmcs.com/hooks-reference/module/#aftermodulecreatefailed).

**Comment by JayRusson** [comment]
Yeah that’s what I was looking at, just tried to describe it minimalistically haha, the actual function works however it’s just the link that I’m struggling with, it needs two variables in the link the user ID and serviceID or just the Service ID Which is what I’m hoping you can work out? I’ve never touched the WHMCS API before

**Comment by metallicgloss** [comment]
The module-related hooks typically kick back an array specific to the module that is associated with the service - these wouldn't be listed on the hook page, but would on the module provisioning page [here](https://developers.whmcs.com/provisioning-modules/module-parameters/) which should include the service ID and user ID that you're looking for. I hope that helps!

Beyond basic bug fixes, should a new version of WHMCS introduce any changes that result in some projects, I'm not actively developing or building out new features for this script myself for the foreseeable future, but if you're able to get it working, and wished to contribute back to the script for others to be able to make use of it, please feel free to open a pull request!

**Comment by JayRusson** [comment]
Yeah that’s what I was looking at, just tried to describe it minimalistically haha, the actual function works however it’s just the link that I’m struggling with, it needs two variables in the link the user ID and serviceID or just the Service ID

**Pull request closed without merging**
